# Tests for (blackcat shepherd defaults)

guile_loads "(blackcat shepherd services )"
guile_loads "(blackcat shepherd services core)"

guile_check "default-services-path is /etc/shepherd.d" \
    {(use-modules (blackcat shepherd services)) (display default-services-path)} \
    "/etc/shepherd.d"

guile_check "%core-services is a list" \
    {(use-modules (blackcat shepherd services core)) (display (list? %core-services))} \
    "#t"

guile_check "%core-services has 13 entries" \
    {(use-modules (blackcat shepherd services core)) (display (length %core-services))} \
    "13"

guile_check "%core-services-service has 13 entries" \
    {(use-modules (blackcat shepherd services core)) (display (length %core-services-service))} \
    "13"

# TODO: service-autoloader will be fixed at a later point
# guile_check "%core-services includes service-autoloader" \
#     {(use-modules (blackcat shepherd services core))
#      (display (if (memq 'service-autoloader %core-services) #t #f))} \
#     "#t"

guile_check "%core-services includes agetty-tty1" \
    {(use-modules (blackcat shepherd services core))
     (display (if (memq 'agetty-tty1 %core-services) #t #f))} \
    "#t"

guile_check "%core-services includes halt-hook" \
    {(use-modules (blackcat shepherd services core))
     (display (if (memq 'halt-hook %core-services) #t #f))} \
    "#t"
