(define-module (blackcat watch)
  #:use-module (blackcat inotify)
  #:export (watch-directory))

(define (watch-directory dir callback)
  (let ((inotify (make-inotify)))
    (inotify-add-watch! inotify dir '(create delete modify moved-from moved-to))
    (let loop ()
      (when (inotify-pending-events? inotify)
        (let ((event (inotify-read-event inotify)))
          (callback (inotify-event-type event)
                    (inotify-event-file-name event))))
      (loop))))
